### ISSUE TITLE
Registering application URL is not working

### ISSUE THREAD

**Issue by kakajan** [quranacademy/digital-quran-docs#3]
As-salamu Alaykum
I had problem to test the API. I cant register the application cause the link doesn't working.
"https://en.quranacademy.org/digital-quran/applications"
would you please help me to figure it out?
Thank you
Jazakum Allahu khairan

**Comment by Imangazaliev** [comment]
Wa alaykum salam, wa iyyakum. API is currently under development, we will release it soon, in shaa Allah. I added a warning to the documentation so as not to confuse other developers.

**Comment by thg303** [comment]
Is there any public repository to contribute API development or it's not supposed to be open-source?

**Comment by Imangazaliev** [comment]
Unfortunately no, because it's a part of Quran Academy website. By the way, yesterday we deployed the API to production, please check it out.

**Comment by rguliev** [comment]
Does it work now? Can we close the issue?

**Comment by Imangazaliev** [comment]
Yes, we can close it.
