### ISSUE TITLE
why not wiki?

### ISSUE THREAD

**Issue by thg303** [quranacademy/digital-quran-docs#4]
Currently, all docs are written in .md files all over the repo. but the problem is it does not allow easy collaboration and contributions. say for example someone likes to suggest something about an API. Do they have to create a PR for that? with [wiki](https://github.com/quranacademy/digital-quran-docs/wiki), it would be much easier to contribute and organize the documentations.

what do you think guys? is there a reason behind this structure?

**Comment by rguliev** [comment]
السلام عليكم

We use GitBook for writing docs. `.md` files are just generated automatically by GitBook. We found GitBook very convenient for writing docs, it has some convenient features.
 Besides, putting docs to GitHub wiki will allow everyone to make changes. You are right, that it would allow easier commits. However, on the other hand, we think that it will make docs a bit messy and difficult to track and discuss changes. The good thing about PRs is that we can discuss changes and suggestions before committing them to the docs.
