### ISSUE TITLE
api documentation options

### ISSUE THREAD

**Issue by thg303** [quranacademy/digital-quran-docs#5]
I think it's a good idea to see our options about what tools do we have to document the API.
I can name a few and we can allow everybody to build their own version on their own favorite documentation tool.

 - [swagger](https://swagger.io/solutions/)
 - [postman](https://www.getpostman.com/)

**Comment by cometofsky** [comment]
or Insomnia

**Comment by Imangazaliev** [comment]
We plan to describe the API in OpenAPI (Swagger) format, in shaa Allah.

**Comment by rguliev** [comment]
@Imangazaliev can we suggest this task to @thg303? I think it is not that difficult and would be a good starting point for participation:)

**Comment by Imangazaliev** [comment]
@rguliev yes, it will be nice if @thg303 hels us with this.

**Comment by thg303** [comment]
@rguliev @Imangazaliev what should I do?

**Comment by Imangazaliev** [comment]
@thg303 just describe the API in OpenAPI format using YAML and put it to `api/openapi` directory.

A little request: please put description of each endpoint in a separate file. Example of an index file (I suggest to name it `api.yml`):

```yaml
openapi: 3.0.2

info:
  version: 1.0.0
  title: "Digital Quran API"

servers:
  - url: https://digital-quran.quranacademy.com
    description: Quran Academy server

paths:
  /languages:
    $ref: ./paths/languages.yml
```

`paths` directory contains files with description of each endpoint.

**Comment by thg303** [comment]
ok, I'll make the PR.
